export const GET_SUPER_ADMINS_PENDING = 'GET_SUPER_ADMINS_PENDING';
export const GET_SUPER_ADMINS_SUCCESS = 'GET_SUPER_ADMINS_SUCCESS';
export const GET_SUPER_ADMINS_ERROR = 'GET_SUPER_ADMINS_ERROR';

export const DELETE_SUPER_ADMINS_SUCCESS = 'DELETE_SUPER_ADMINS_SUCCESS';

export const EDIT_SUPER_ADMIN_PENDING = 'EDIT_SUPER_ADMIN_PENDING';
export const EDIT_SUPER_ADMIN_SUCCESS = 'EDIT_SUPER_ADMIN_SUCCESS';
export const EDIT_SUPER_ADMIN_ERROR = 'EDIT_SUPER_ADMIN_ERROR';

export const SUPER_ADMIN_MODAL = 'SUPER_ADMIN_MODAL';
export const SUPER_ADMIN_MODAL_CONTENT = 'SUPER_ADMIN_MODAL_CONTENT';
