export const GET_SUPER_ADMINS_PENDING = 'GET_SUPER_ADMINS_PENDING';
export const GET_SUPER_ADMINS_FULFILLED = 'GET_SUPER_ADMINS_FULFILLED';
export const GET_SUPER_ADMINS_REJECTED = 'GET_SUPER_ADMINS_REJECTED';
