export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';

export const EDIT_EMPLOYEE_PENDING = 'EDIT_EMPLOYEE_PENDING';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_ERROR = 'EDIT_EMPLOYEE_ERROR';

// export const ADD_EMPLOYEES_SUCCESS = 'ADD_EMPLOYEES_SUCCESS';
// export const ADD_EMPLOYEES_ERROR = 'ADD_EMPLOYEES_ERROR';

export const EMPLOYEE_SHOW_MODAL = 'EMPLOYEE_SHOW_MODAL';
export const EMPLOYEE_NODAL_CONTENT = 'EMPLOYEE_NODAL_CONTENT';
