export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const CREATE_TASKS_PENDING = 'CREATE_TASKS_PENDING';
export const CREATE_TASKS_SUCCESS = 'CREATE_TASKS_SUCCESS';
export const CREATE_TASKS_ERROR = 'CREATE_TASKS_ERROR';

export const EDIT_TASKS_PENDING = 'EDIT_TASKS_PENDING';
export const EDIT_TASKS_SUCCESS = 'EDIT_TASKS_SUCCESS';
export const EDIT_TASKS_ERROR = 'EDIT_TASKS_ERROR';

export const DELETE_TASKS_PENDING = 'DELETE_TASKS_PENDING';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_ERROR = 'DELETE_TASKS_ERROR';
