export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';

export const PUT_PROJECTS_PENDING = 'PUT_PROJECTS_PENDING';
export const PUT_PROJECTS_SUCCESS = 'PUT_PROJECTS_SUCCESS';
export const PUT_PROJECTS_ERROR = 'PUT_PROJECTS_ERROR';

export const POST_PROJECTS_PENDING = 'POST_PROJECTS_PENDING';
export const POST_PROJECTS_SUCCESS = 'POST_PROJECTS_SUCCESS';
export const POST_PROJECTS_ERROR = 'POST_PROJECTS_ERROR';

export const DELETE_PROJECTS_PENDING = 'DELETE_PROJECTS_PENDING';
export const DELETE_PROJECTS_SUCCESS = 'DELETE_PROJECTS_SUCCESS';
export const DELETE_PROJECTS_ERROR = 'DELETE_PROJECTS_ERROR';
