export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const SET_LOGGED_OUT = 'SET_LOGGED_OUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';

export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
